description: Loading information about systems and their types into tuning.search_system_x_type table
schedule_interval: 12 05 * * *
tags:
  - tuning
default_args:
  owner: airflow
  result_type: pickle
  retries: 1
  work_conn_id: s3work
  work_type: s3
factory: Python
