description: Loading entity relationship types
schedule_interval: 12 12 * * *
tags:
  - tuning
default_args:
  owner: airflow
  result_type: pickle
  retries: 1
  work_conn_id: s3work
  work_type: s3
factory: Python
